.github/workflows/testing.yml

fix: 暂时屏蔽语法检查

---

.github/workflows/release.yml

feat: add version to build.sh

---

Dockerfile
deploy/configmap/polaris-client-config.yaml
deploy/configmap/polaris-sidecar-config.yaml

polaris-sidecar容器

---

README.md
deploy/spec/sidecar-dns-example.yaml

feat：增加容器化部署的配置文件及文档

---

cmd/start.go
deploy/dnsagent/deployment-dnsagent.yaml

feat: polaris-sidecar支持容器化部署

---

README.md
deploy/dnsagent/deployment-dnsagent.yaml

feat: 增加容器化部署指南

---

build_docker.sh

build: 调整polaris-sidecar镜像构建脚本

---

.github/workflows/docker.yml
deploy/k8s/configmap-polaris-client.yaml
go.mod
go.sum
polaris.yaml

feat: 支持就近路由

---

deploy/vm/install-linux.sh
deploy/vm/uninstall-linux.sh
polaris.yaml

fix: 修复VM的快速polaris-sidecar安装命令问题

---

bootstrap/dns.go
resolver/dnsagent/plugin.go

[ISSUE #28] fix issue #28

---

README-zh.md
README.md

docs: update readme

---

build_docker.sh
go.mod
go.sum
polaris-sidecar.yaml
resolver/meshproxy/config.go
resolver/meshproxy/plugin.go
resolver/meshproxy/registry_proxy.go

feat：支持通过北极星拉取服务列表

---

build_docker.sh

feat: 非prerelease版本才打latest

---

bootstrap/config.go
go.mod
go.sum
polaris-sidecar.yaml
resolver/meshproxy/dns.go
resolver/meshproxy/plugin.go

feat：add logs

---

resolver/meshproxy/dns.go
resolver/meshproxy/plugin.go
resolver/meshproxy/registry_proxy.go

优化getcurrentservice，减少循环

---

Dockerfile
bootstrap/agent.go
bootstrap/config.go
bootstrap/mtls.go
cmd/start.go
go.mod
go.sum
security/mtls/agent/agent.go
security/mtls/agent/option.go
security/mtls/agent/serviceaccount.go
security/mtls/certificate/bundle.go
security/mtls/certificate/caclient/client.go
security/mtls/certificate/caclient/client_test.go
security/mtls/certificate/caclient/sat.go
security/mtls/certificate/manager/interface.go
security/mtls/certificate/manager/manager.go
security/mtls/rotator/rotate.go
security/mtls/sds/secret.go
security/mtls/sds/server.go

Fixes #
- [*] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

[feat] Support mTLS Server

---

Dockerfile
bootstrap/agent.go
bootstrap/config.go
bootstrap/config_test.go
bootstrap/consts.go
bootstrap/dns.go
bootstrap/mtls.go
cmd/start.go
polaris-sidecar.yaml
polaris.yaml
resolver/dnsagent/config.go
resolver/dnsagent/plugin.go
resolver/meshproxy/plugin.go
resolver/resolver.go

feat: 修复dns域名替换的问题

---

bootstrap/agent.go
bootstrap/config.go
cmd/start.go

feat: 增加原有sidecar的兼容逻辑

---

.github/workflows/release.yml

feat: intel在arm编译失败，暂时先不出arm的包

---

Dockerfile

feat: 增加路径启动命令

---

bootstrap/agent.go

mtls增加开关的判断

---

resolver/meshproxy/dns.go
resolver/meshproxy/plugin.go

feat: 修复DN解释的问题

---

bootstrap/dns.go

feat：sidecar增加DNS解释日志

---

security/mtls/sds/secret.go

fix: wrong cpuid check method

---

bootstrap/config.go
bootstrap/config_test.go
bootstrap/consts.go
bootstrap/dns.go
polaris-sidecar.yaml
resolver/dnsagent/plugin.go
resolver/resolver.go
resolver/util.go

fix: 解决DNS agent默认命名空间解释失败问题

---

bootstrap/config.go
bootstrap/config_test.go
bootstrap/consts.go
polaris-sidecar.yaml
resolver/dnsagent/plugin.go
resolver/resolver.go
resolver/util.go

fix: 解决缺失命名空间导致dns解释问题问题 (#53)

---

.github/workflows/docker.yml
.github/workflows/package.yaml
.github/workflows/release.yml
.github/workflows/testing.yml
go.mod
metrics/server.go

feat: 修改编译问题

---

README-zh.md
README.md

docs: 修复文档失效的链接

---

Dockerfile

fix:dockerfile build fail
